### ISSUE TITLE
[homeassistant.components.cover] Error while setting up platform myq

### ISSUE THREAD

**Issue by haalpplz** [arraylabs/myq#7]
Started getting the error below out of nowhere. Not sure what the issue is, my myq wont load anymore. Any ideas?

```
17-02-14 19:08:47 ERROR (MainThread) [homeassistant.components.cover] Error while setting up platform myq
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 64, in setup_platform
    add_devices(MyQCoverDevice(myq, door) for door in myq.get_garage_doors())
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 144, in get_garage_doors
    devices = self.get_devices()
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 122, in get_devices
    self._logged_in = self.login()
  File "/home/homeassistant/.homeassistant/custom_components/cover/myq.py", line 113, in login
    auth = login.json()
  File "/srv/homeassistant/lib/python3.4/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by arraylabs** [comment]
Have you updated the myq.py file in the last couple days? I posted a new one earlier today. The endpoints changed again yesterday.

**Comment by haalpplz** [comment]
Ah, thanks. That did it. I should have checked for an update first. Thank you!!

**Comment by arraylabs** [comment]
No problem, glad you got things going again. Keep an eye out for HA 0.39 where its an official component.
